version: '3.8'

volumes:
  mongodb-data:
    name: mongodb-data
  mongo-express-data:

networks:
  mongodb-network:
    name: mongodb-network

services:
  app_python:
    container_name: ${APP_CONTAINER_NAME}
    hostname: ${APP_HOSTNAME}
    build:
      context: .
      dockerfile: ./docker/app_python/Dockerfile
    env_file:
      - ./config/env.dev
    environment:
      FLASK_APP: AppTest.py
      FLASK_ENV: development
      FLASK_DEBUG: 1
    volumes:
      - ./app_python/:/app_python/
    ports:
      - "5000:5000"
    networks:
      - mongodb-network


  mongodb:
    image: mongo:3.6.22
    container_name: ${MONGO_CONTAINER_NAME}
    hostname: ${MONGO_HOSTNAME}
    restart: unless-stopped
    user: "mongodb:mongodb"
    volumes:
      - ./docker/mongodb/configdb/mongod.conf:/etc/mongod.conf
      - ./docker/mongodb/initdb.d/mongo-init.sh:/docker-entrypoint-initdb.d/mongo-init.sh
      - /var/lib/mongodb/data/db:/data/db
      - /var/lib/mongodb/data/log:/var/log/mongodb
      - /var/lib/mongodb/data/home:/home/mongodb # in order to has the history of the shell .dbshell  in /home/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_USERNAME: ${MONGO_INITDB_USERNAME}
      MONGO_INITDB_PASSWORD: ${MONGO_INITDB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    ports:
      - "27017:27017"
    networks:
      - mongodb-network


  mongo-express:
    image: mongo-express:0.54.0
    container_name: ${ME_CONTAINER_NAME}
    hostname: ${MONGO_CONTAINER_NAME}
    restart: unless-stopped
    volumes:
      - ./docker/mongo-express/docker-entrypoint.sh:/docker-entrypoint.sh
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "true"
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      ME_CONFIG_BASICAUTH_USERNAME: ${ME_CONFIG_BASICAUTH_USERNAME}
      ME_CONFIG_BASICAUTH_PASSWORD: ${ME_CONFIG_BASICAUTH_PASSWORD}
    networks:
      - mongodb-network
    depends_on:
      - mongodb
